  version: '3'

  services:
    spark:
      build: Spark/.
      networks:
        - dbnet
      ports:
        - "8888:8888"
        - "4040-4049:4040-4049"
    postgis:
      build: PostgreSQL/.
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      networks:
        - dbnet
      ports:
        - "5432:5432"  
    mysql:
      build: MySQL/.
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
      networks:
        - dbnet
      ports:
        - "3306:3306"   
    mongo:
      build: MongoDB/.
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=mongodb
      networks:
        - dbnet
      ports:
        - "27017:27017"
    zookeeper:
      image: docker.io/bitnami/zookeeper:3.8
      networks:
        - dbnet
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
      image: docker.io/bitnami/kafka:3.3
      networks:
        - dbnet
      ports:
        - "9092:9092"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper
  networks:
    dbnet: